import { useEffect } from 'react';
import Head from 'next/head';
import { Header } from '..';

export function Layout({
    children,
    generalSettings,
    mainMenu,
    socialMenu,
    title,
    isHome,
}: {
    children: React.ReactNode;
    generalSettings: WPAPI.GeneralSettingsProps;
    mainMenu: WPAPI.MenuProps;
    socialMenu: WPAPI.MenuProps;
    title: string;
    isHome?: boolean;
}): JSX.Element {
    useEffect(() => {
        document.documentElement.lang = 'en';
    }, []);
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="color-scheme" content="dark light" />
                <link rel="icon" href="/favicon.ico" />
                {/* <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="anonymous"
                /> */}
                <link
                    rel="preconnect"
                    href="https://fonts.googleapis.com"
                    crossOrigin="anonymous"
                />
            </Head>
            <Header
                mainMenu={mainMenu}
                socialMenu={socialMenu}
                isHome={isHome}
                generalSettings={generalSettings}
            />

            <main>{children}</main>
        </div>
    );
}
