import Head from 'next/head';
import { Header } from '..';

export function Layout({
    children,
    generalSettings,
    mainMenu,
    socialMenu,
    title,
    isHome,
}: {
    children: React.ReactNode;
    generalSettings: WPAPI.GeneralSettingsProps;
    mainMenu: WPAPI.MenuProps;
    socialMenu: WPAPI.MenuProps;
    title: string;
    isHome?: boolean;
}): JSX.Element {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header
                mainMenu={mainMenu}
                socialMenu={socialMenu}
                isHome={isHome}
                generalSettings={generalSettings}
            />
            <main>{children}</main>
        </div>
    );
}
