import { GetStaticProps } from 'next';
import Head from 'next/head';
import { AuthorBio, HomeProjects, Skills, Header } from '../components/';
import { getAllHomeProjects, getAuthorBio, getAllSkills } from '../lib/api-wp';
import { HomeProjectsProps, SkillsProps, AuthorBioProps } from '../components/';

interface HomeProps {
    homeProjects: HomeProjectsProps;
    authorBio: AuthorBioProps;
    allSkills: SkillsProps;
}

export default function Home({
    homeProjects,
    authorBio,
    allSkills,
}: HomeProps): JSX.Element {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Portfolio Theme</h1>
                <AuthorBio {...authorBio} />
                <Skills allSkills={allSkills} />
                <HomeProjects homeProjects={homeProjects} />
            </main>
        </div>
    );
}

export const getStaticProps: GetStaticProps = async function () {
    const homeProjects = await getAllHomeProjects();
    const authorBio = await getAuthorBio();
    const allSkills = await getAllSkills();
    return {
        props: { homeProjects, authorBio, allSkills },
    };
};
