import Head from 'next/head';
import styles from '../sass/Home.module.scss';
import { getAllProjects, getAuthorBio, getAllSkills } from '../lib/api-wp';
import Image from 'next/image';
import Link from 'next/link';

export default function Home({ allPosts, authorBio, allSkills }) {
    console.log(allSkills);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Portfolio Theme</h1>
                <section>
                    <h2>{authorBio.authorBios.authorsName}</h2>
                    <h3>{authorBio.authorBios.authorTagLine}</h3>
                    <div
                        dangerouslySetInnerHTML={{ __html: authorBio.excerpt }}
                    />
                    <Image
                        src={authorBio.authorBios.authorPic.sourceUrl}
                        width={250}
                        height={250}
                        objectFit={'cover'}
                        objectPosition={'top right'}
                    />
                </section>
                <section>
                    <ul>
                        {allSkills.map(({ node: { slug, name } }) => {
                            return (
                                <li key={slug}>
                                    <Link href={`/skills/${slug}`}>
                                        <a>{name}</a>
                                    </Link>
                                </li>
                            );
                        })}
                    </ul>
                </section>
                <section>
                    <ul>
                        {allPosts.map(
                            ({
                                node: {
                                    title,
                                    slug,
                                    featuredImage: {
                                        node: { sourceUrl },
                                    },
                                    projectFields: {
                                        projectDescription,
                                        linkToLiveSite,
                                        repoLink,
                                    },
                                },
                            }) => (
                                <li key={slug} id={slug}>
                                    <h2>{title}</h2>

                                    <div
                                        style={{
                                            position: 'relative',
                                            height: '22vh',
                                            width: '400px',
                                        }}
                                    >
                                        <Image
                                            src={sourceUrl}
                                            layout="fill"
                                            objectFit={'cover'}
                                            objectPosition={'top left'}
                                        />
                                    </div>
                                    <p>{projectDescription}</p>
                                    <b>{slug}</b>
                                    <a href={linkToLiveSite} target="_blank">
                                        {linkToLiveSite}
                                    </a>
                                    <a href={repoLink} target="_blank">
                                        {repoLink}
                                    </a>
                                    <div>
                                        <Link href={`/projects/${slug}`}>
                                            <a>{slug}</a>
                                        </Link>
                                    </div>
                                </li>
                            )
                        )}
                    </ul>
                </section>
            </main>
        </div>
    );
}

export async function getStaticProps() {
    const allPosts = await getAllProjects();
    const authorBio = await getAuthorBio();
    const allSkills = await getAllSkills();
    return {
        props: { allPosts, authorBio, allSkills },
    };
}
