import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import AuthorBio from '../components/AuthorBio/AuthorBio';
import Skills from '../components/Skills/Skills';
import HomeProjects from '../components/HomeProjects/HomeProjects';
import styles from '../sass/Home.module.scss';
import { getAllHomeProjects, getAuthorBio, getAllSkills } from '../lib/api-wp';
import { AuthorBioProps } from '../components/AuthorBio/AuthorBio';
import { SkillsProps } from '../components/Skills/Skills';
import { HomeProjectsProps } from '../components/HomeProjects/HomeProjects';

interface HomeProps {
    homeProjects: HomeProjectsProps;
    authorBio: AuthorBioProps;
    allSkills: SkillsProps;
}

export default function Home({
    homeProjects,
    authorBio,
    allSkills,
}: HomeProps) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Portfolio Theme</h1>
                <AuthorBio {...authorBio} />
                <Skills allSkills={allSkills} />
                <HomeProjects homeProjects={homeProjects} />
            </main>
        </div>
    );
}

export const getStaticProps: GetStaticProps = async function () {
    const homeProjects = await getAllHomeProjects();
    const authorBio = await getAuthorBio();
    const allSkills = await getAllSkills();
    return {
        props: { homeProjects, authorBio, allSkills },
    };
};
